### ISSUE TITLE
Awesome script .....Stuck with no cpu, hdd, or network activity

### ISSUE THREAD

**Issue by liamgibbins** [AlanYoon71/0L_Installation#1]
Awesome script, so much easier.

I am currently stuck on compiling OL Binary, I have no cpu, hdd or network activity for that server.
Its been running for over an hour and a half should I just wait for it to see if it comes back to life?

..Compiling 0l binary files.. 
====================

This script includes genesis mining and tower, so it takes 1 hour more entirely until all processes completed, so be patient, please.

Script for TMUX background started.

**Comment by AlanYoon71** [comment]
Open another terminal and enter "tmux attach - onboarding" to check the progress owner status.
If there is an error and the compilation has stopped, it may be better to look at the official guide document and follow the steps by step.

________________________________
보낸 사람: liamgibbins ***@***.***>
보낸 날짜: 2023년 5월 19일 금요일 오후 5:17
받는 사람: AlanYoon71/0L_Installation ***@***.***>
참조: Subscribed ***@***.***>
제목: [AlanYoon71/0L_Installation] Awesome script .....Stuck with no cpu, hdd, or network activity (Issue #1)


Awesome script, so much easier.

I am currently stuck on compiling OL Binary, I have no cpu, hdd or network activity for that server.
Its been running for over an hour and a half should I just wait for it to see if it comes back to life?

..Compiling 0l binary files..

This script includes genesis mining and tower, so it takes 1 hour more entirely until all processes completed, so be patient, please.

Script for TMUX background started.

**Comment by AlanYoon71** [comment]
.
